name: Paper_summaries

on:
  schedule:
    - cron: '00 12 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      # Installiere erforderliche Abhängigkeiten
      - name: Install dependencies
        run: |
          pip install langchain_openai langchain langchain_community requests beautifulsoup4 sentence-transformers chromadb

      # - name: Run llm OpenAI
      #   env:
      #     USER_EMAIL: ${{ secrets.USER_EMAIL }}
      #     USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      #     OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          
      #   run: python Scripts/github_actions/OpenAI.py
      
      - name: Run llm Mistral_2
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
        run: python Scripts/github_actions/Mistral_2.py
