name: Paper_summaries

on:
  schedule:
    - cron: '00 12 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      # Neuer Schritt, um Abhängigkeiten zu installieren
      - name: Install dependencies
        run: |

      - name: Run email code
        env:
          USER_EMAIL: ${{ secrets.OPENAI_TOKEN }}
          
        run: python Scripts/OpenAI.py